"""PR Node - Commit, push, create Pull Request with RCA."""

from __future__ import annotations

import os

from src.orchestrator.state import PhoenixState
from src.services.github_client import commit_and_push, create_pull_request


def _build_rca_body(state: PhoenixState) -> str:
    """Build RCA (Root Cause Analysis) for PR description."""
    error = state.get("error_summary", "")
    stack = state.get("stack_trace", "")
    file_path = state.get("file_path", "")
    angular = state.get("angular_version", "")
    node_ver = state.get("node_version", "")

    lines = [
        "## 🔧 Project Phoenix — Auto-generated Fix",
        "",
        "### Root Cause Analysis",
        "",
        f"**Error:** `{error}`",
        "",
        f"**Stack trace:**",
        "```",
        stack or "(not provided)",
        "```",
        "",
        "### Fix Summary",
        "- Fixed via Opus 4.6",
        f"- File: `{file_path}`" if file_path else "",
        f"- Angular: {angular}" if angular else "",
        f"- Node: {node_ver}" if node_ver else "",
        "",
        "### Validation",
        "- ✅ ng build passed",
        "- ✅ ng lint passed",
        "",
        "---",
        "*Generated by Project Phoenix — Self-Healing Agent*",
    ]
    return "\n".join(line for line in lines if line)


def _owner_from_url(url: str) -> str:
    """Extract owner from URL. e.g. https://github.com/jitendershiprocket/SR_Web -> jitendershiprocket"""
    url = url.rstrip("/").replace(".git", "")
    parts = [p for p in url.split("/") if p and p not in ("https:", "http:")]
    return parts[-2] if len(parts) >= 2 else ""


def pr_node(state: PhoenixState) -> dict:
    """Commit, push, and create PR via GitHub API."""
    repo_path = state.get("repo_path", "")
    fix_branch = state.get("fix_branch", "")
    repo_url = state.get("repo_url", "")  # fork URL - push goes to origin (this)
    upstream_url = state.get("upstream_url", "")
    base_branch = state.get("branch", "main")
    error_summary = state.get("error_summary", "")

    if not repo_path or not fix_branch or not repo_url:
        return {"status": "failed", "pr_url": None, "validation_log": "Missing repo_path, fix_branch, or repo_url"}

    if not state.get("fix_applied", False):
        reason = state.get("fix_failure_reason", "No fix was applied (file resolution failed or fix skipped)")
        return {"status": "failed", "pr_url": None, "validation_log": reason}

    token = os.getenv("GITHUB_TOKEN")
    if not token:
        return {"status": "failed", "pr_url": None, "validation_log": "GITHUB_TOKEN required for PR"}

    # Commit message
    short_error = (error_summary[:60] + "…") if len(error_summary) > 60 else error_summary
    commit_msg = f"fix: {short_error}\n\n[Project Phoenix auto-fix]"

    # 1. Commit and push — when upstream_url, push directly to bfrs (no fork)
    push_remote = "upstream" if upstream_url else "origin"
    ok, msg = commit_and_push(repo_path, fix_branch, commit_msg, token, push_remote=push_remote)
    if not ok:
        return {"status": "failed", "pr_url": None, "validation_log": f"Push failed: {msg}"}

    # 2. Create PR — same repo (bfrs), head=fix_branch, base=ng_19_9may
    title = f"fix: {short_error}"
    body = _build_rca_body(state)
    pr_base_url = upstream_url or repo_url
    head_ref = fix_branch
    pr_url, err = create_pull_request(
        repo_url=pr_base_url,
        fix_branch=head_ref,
        base_branch=base_branch,
        title=title,
        body=body,
        token=token,
    )
    if err:
        return {"status": "failed", "pr_url": None, "validation_log": f"PR create failed: {err}"}

    return {"status": "success", "pr_url": pr_url}
